"""empty message

Revision ID: 1bb0a5841428
Revises: 
Create Date: 2020-03-04 17:43:46.065650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb0a5841428'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('type_recipe', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('most_recent_search', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('num_searches', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('search_id_1', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('search_id_2', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('search_id_3', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('search_id_4', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('search_id_5', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('search_string_1', sa.String(length=280), nullable=True))
    op.add_column('user', sa.Column('search_string_2', sa.String(length=280), nullable=True))
    op.add_column('user', sa.Column('search_string_3', sa.String(length=280), nullable=True))
    op.add_column('user', sa.Column('search_string_4', sa.String(length=280), nullable=True))
    op.add_column('user', sa.Column('search_string_5', sa.String(length=280), nullable=True))
    op.add_column('user', sa.Column('secret', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('two_factor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'two_factor')
    op.drop_column('user', 'secret')
    op.drop_column('user', 'search_string_5')
    op.drop_column('user', 'search_string_4')
    op.drop_column('user', 'search_string_3')
    op.drop_column('user', 'search_string_2')
    op.drop_column('user', 'search_string_1')
    op.drop_column('user', 'search_id_5')
    op.drop_column('user', 'search_id_4')
    op.drop_column('user', 'search_id_3')
    op.drop_column('user', 'search_id_2')
    op.drop_column('user', 'search_id_1')
    op.drop_column('user', 'num_searches')
    op.drop_column('user', 'most_recent_search')
    op.drop_column('recipes', 'type_recipe')
    # ### end Alembic commands ###
